### PR TITLE
implement ci check_data_consistency

### PR DESCRIPTION
**Pull request by alexfoias**

### CODE REVIEW

**Comment by alexfoias** [comment]
Output from the current master:
```
(base) alfoi@MacBook-Pro:data-single-subject % sg_check_data_consistency -path-in ./
Missing jsonSidecar: ./derivatives/labels/sub-oxfordFmrib/anat/sub-oxfordFmrib_T1w_RPI_r_labels-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-oxfordFmrib/anat/sub-oxfordFmrib_T1w_RPI_r_seg-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-douglas/anat/sub-douglas_T1w_RPI_r_labels-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-juntendoAchieva/dwi/sub-juntendoAchieva_dwi_moco_dwi_mean_seg-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-tokyoSigna2/dwi/sub-tokyoSigna2_dwi_moco_dwi_mean_seg-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-tokyoSigna2/anat/sub-tokyoSigna2_T1w_RPI_r_seg-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-perform/dwi/sub-perform_dwi_moco_dwi_mean_seg-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-perform/anat/sub-perform_T1w_RPI_r_labels-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-perform/anat/sub-perform_T1w_RPI_r_seg-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-tokyo750w/dwi/sub-tokyo750w_dwi_moco_dwi_mean_seg-manual.json
Missing jsonSidecar: ./derivatives/labels/sub-ucl/anat/sub-ucl_T1w_RPI_r_labels-manual.json
```

**Comment by alexfoias** [comment]
@jcohenadad This PR is ready for review.

**Review by jcohenadad — APPROVED** [review]

**Comment by alexfoias** [comment]
I suppose we wait as for data-multi-subject.

**Comment by jcohenadad** [comment]
> I suppose we wait as for data-multi-subject.

no we don't-- @kousu hasn't git-annexed this repos (yet)

**Comment by kousu** [comment]
Ah, nope. But it won't be hard to do that. But you should commit this as is and I'll annex it after that.

**Comment by kousu** [comment]
I've done the migration: #7.

Since this patch is so small, want to just remake it in the annexed repo?

I also made changes to the CI script (https://github.com/spine-generic/data-multi-subject/pull/6) that this should be merged with.

**Comment by jcohenadad** [comment]
Implemented in https://github.com/spine-generic/data-single-subject/commit/4cd64e35fd0ea1b168c7edef7245aeba046807d4

**Pull request closed without merging**
